<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID_invalid_alert_message</name>
   <tag></tag>
   <elementGuidId>111348cb-a1bc-45d7-91a6-b7580af273a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='invalidLoginNoCaptcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invalidLoginNoCaptcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1309787f-ac1e-4309-be54-688fdc84332a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invalidLoginNoCaptcha</value>
      <webElementGuid>b16e22d7-422a-4799-9e61-27801302eb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>6b3892e7-6cb8-47de-ad32-87d88397f109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account protected from login. Please contact Customer Service for assistance.</value>
      <webElementGuid>d6b9dc05-fd5e-4685-b413-d5883bda1ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invalidLoginNoCaptcha&quot;)</value>
      <webElementGuid>72b37c6a-b427-4fe6-ac2e-06e9dac6c6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='invalidLoginNoCaptcha']</value>
      <webElementGuid>85d149a5-05e7-4687-b944-3c37a50ea194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginFormByLoginNameOrEmail']/span</value>
      <webElementGuid>6bd57998-a9d2-40d5-8e0c-5e2813b2118c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::span[1]</value>
      <webElementGuid>53497d20-4a63-4be1-b3e7-8b4aa5565041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::span[1]</value>
      <webElementGuid>15c9d0dc-cf42-44e7-a426-3daa169dd371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::span[1]</value>
      <webElementGuid>4817059a-eb5d-4fb4-9378-377d853ec890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us Now!'])[1]/preceding::span[1]</value>
      <webElementGuid>5d7ab3bb-7824-4dbf-b189-6111f25c5840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account protected from login. Please contact Customer Service for assistance.']/parent::*</value>
      <webElementGuid>abd4f516-0e50-44b3-bd51-6b9892f83adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span</value>
      <webElementGuid>53c3d400-6512-495f-9b07-04e615ab462a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'invalidLoginNoCaptcha' and (text() = 'Account protected from login. Please contact Customer Service for assistance.' or . = 'Account protected from login. Please contact Customer Service for assistance.')]</value>
      <webElementGuid>1556bf62-78a5-40d6-93b2-52e2fab976d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
