<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , K_L_D_Iframe, , ))_K_L_D_Iframe</name>
   <tag></tag>
   <elementGuidId>34c9f0fa-0f23-4fe0-b51f-0c3ef7160ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='K_L_D_Iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K_L_D_Iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3db627dd-5f77-4f13-8faf-4315f12922d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K_L_D_Iframe</value>
      <webElementGuid>60c99dc3-6ac0-4089-a7a7-4915101f70e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://livech901.com/chat_online/index?channelId=c5559e939d9342c694c075e02092db3d&amp;locale=en&amp;userId=&amp;pid=&amp;userName=&amp;inviteEvaluate=true&amp;close=true&amp;auto=true&amp;autoTime=1000&amp;from=iframe&amp;random=1</value>
      <webElementGuid>3e09bc23-e50b-4a7c-bd7d-d53a1b4bcd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K_L_D_Iframe&quot;)</value>
      <webElementGuid>1a05d362-afc2-491a-aab9-4fe9b2fa35d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='K_L_D_Iframe']</value>
      <webElementGuid>6115a59e-a945-4c5f-9056-43b94aec8c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='livechat_btn_id']/div[2]/iframe</value>
      <webElementGuid>37fd6aa9-5393-45bf-b06b-ce5000c37857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>79c9e582-af9b-4f4c-ab45-27e4e0a17b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'K_L_D_Iframe' and @src = 'https://livech901.com/chat_online/index?channelId=c5559e939d9342c694c075e02092db3d&amp;locale=en&amp;userId=&amp;pid=&amp;userName=&amp;inviteEvaluate=true&amp;close=true&amp;auto=true&amp;autoTime=1000&amp;from=iframe&amp;random=1']</value>
      <webElementGuid>662effad-ccfb-4fd4-83be-88c68e010117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
