<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__UserIdentifier</name>
   <tag></tag>
   <elementGuidId>faca8fda-5aa0-474c-8250-0df03cd1a8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputUserIdentifier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputUserIdentifier</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>397eb4bd-32a0-4d5b-8b97-56d8c7b9ba76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserIdentifier</value>
      <webElementGuid>2a7ddced-72a7-49ea-827b-732a6799acdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f245f09-6c29-4508-aff0-215992976912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4c3b2032-50af-4436-ae0d-2884c12a7669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputUserIdentifier</value>
      <webElementGuid>ac4996a7-86ae-468f-b8f2-05ce2f045852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Login Name/ Email</value>
      <webElementGuid>33b99047-b3ac-4fc0-b324-3b9e9c839e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFormByLoginNameOrEmail&quot;)/div[@class=&quot;col-md-6 col-lg-6 col-xl-6 col-lg-offset-2 col-md-offset-2 col-xl-offset-2&quot;]/div[@class=&quot;col-md-5 col-lg-5 col-xl-5 pad-2&quot;]/div[@class=&quot;form-group has-feedback&quot;]/input[@id=&quot;inputUserIdentifier&quot;]</value>
      <webElementGuid>d4036793-c8bb-476d-a3da-92964537cd20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputUserIdentifier']</value>
      <webElementGuid>178f0ea8-c29d-46bf-8ca5-b7803f98005e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginFormByLoginNameOrEmail']/div/div[2]/div/input</value>
      <webElementGuid>7f427981-e8e1-45fb-b058-287f7e3214a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2785af2e-c959-47a6-bcaf-2dc00a950af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'UserIdentifier' and @type = 'text' and @id = 'inputUserIdentifier' and @placeholder = 'Login Name/ Email']</value>
      <webElementGuid>66468bb7-83df-45b7-a60b-ac440aa105b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
